version: 3
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@playwright/test"
      - dependency-name: "exceljs"
    open-pull-requests-limit: 10
    reviewers:
      - "imshaiknasir"
    assignees:
      - "imshaiknasir"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"